In [2]:
import numpy as np

In [3]:
arr  = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
a = [1,2,3.5,"hello"]
a

[1, 2, 3.5, 'hello']

In [5]:
np.array(a)

array(['1', '2', '3.5', 'hello'], dtype='<U32')

In [6]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array generation funcation

In [8]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [9]:
arr = np.zeros((5,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

random genration function

In [12]:
np.random.rand(10)

array([0.22188245, 0.00637272, 0.01794763, 0.64903775, 0.59156135,
       0.24668753, 0.93422244, 0.32916514, 0.37336833, 0.21677338])

In [13]:
np.random.randn(10)

array([-1.03891741, -1.25283436,  0.05356188,  0.56975527, -1.22524386,
       -0.01906975,  0.18201018, -0.71018526,  0.79355496,  0.72543139])

In [15]:
np.random.randint(10,20,10)

array([10, 15, 11, 16, 14, 11, 12, 13, 15, 18], dtype=int32)

Array Attributes

In [16]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr.shape

(3, 3)

In [18]:
arr.size

9

In [19]:
arr.dtype

dtype('int64')

Array methods

In [20]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr.min()

np.int64(1)

In [22]:
arr.max()

np.int64(9)

In [23]:
arr.sum()

np.int64(45)

In [26]:
np.sum(arr,axis = 0)

array([12, 15, 18])

In [28]:
arr.mean()

np.float64(5.0)

In [29]:
arr.std()

np.float64(2.581988897471611)

In [30]:
arr.argmax()

np.int64(8)

In [31]:
arr.argmin()

np.int64(0)

reshaping and resizing

In [37]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [39]:
arr.reshape(6,5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

Numpy array indexing

In [40]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [43]:
arr_slice =arr[1::5]
arr_slice

array([12, 17])

In [44]:
arr[4]

np.int64(15)

numpy array indexing and slicing of matrix

In [45]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [52]:
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [54]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

beloon  indexing

In [56]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [58]:
bool_index = arr %2 ==0 
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [59]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

array opertions

In [60]:
import numpy as np

In [61]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a1

array([1, 2, 3, 4, 5])

In [62]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [63]:
a1-a2

array([-5, -5, -5, -5, -5])

In [64]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [65]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])